### ISSUE TITLE
Why it is calling as Medical Chatbot?

### ISSUE THREAD

**Issue by razakpm** [AIAnytime/Llama2-Medical-Chatbot#11]
What makes this a “medical chatbot?”
is there medical training?
Any helpful documentation know more about it?

**Comment by ashusnapx** [comment]
the data folder is having some thesis paper regarding something medical, thats why it is trained on medical terms, if you want to use yours, just delete that PDF and add yours. Close this issue, if you feel like your issue is solved. Thank You.
