### ISSUE TITLE
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64d23a76-223c75184c82f38733ae8e33;9906dc7e-c132-423c-99c9-463af43648a8)

### ISSUE THREAD

**Issue by margish100** [AIAnytime/Llama2-Medical-Chatbot#6]
Repository Not Found for url: https://huggingface.co/api/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

@AIAnytime Please help me out on this issue

**Comment by margish100** [comment]
sentence-transformers/all-MiniLM-L6-v2ile "/home/developer/Desktop/Llama2-Medical-Chatbot/vnv/lib/python3.10/site-packages/transformers/utils/hub.py", line 433, in cached_file
    raise EnvironmentError(
OSError: private/model is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by Alaa-Mohammad** [comment]
yes repository Not Found for url: https://huggingface.co/api/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main.
Please make sure you specified the correct repo_id and repo_type.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password. i get also this error

**Comment by manjunathshiva** [comment]
In line 43 of model.py update the model as shown below
 model = "TheBloke/Llama-2-7B-Chat-GGML",
